const restaurantdb = require('./restaurantdb/restaurantdb.service.js');
const restaurants = require('./restaurants/restaurants.service.js');
const restschedule = require('./restschedule/restschedule.service.js');
const customers = require('./customers/customers.service.js');
const customService = require('./custom-service/custom-service.service.js');
const addresses = require('./addresses/addresses.service.js');
const cities = require('./cities/cities.service.js');
const countries = require('./countries/countries.service.js');
const menu = require('./menu/menu.service.js');
const menuCategories = require('./menu-categories/menu-categories.service.js');
const restaurantDishes = require('./restaurant-dishes/restaurant-dishes.service.js');
const restDishSizes = require('./rest-dish-sizes/rest-dish-sizes.service.js');
const dishSizes = require('./dish-sizes/dish-sizes.service.js');
const dishesInMenu = require('./dishes-in-menu/dishes-in-menu.service.js');
const scheduleItems = require('./schedule-items/schedule-items.service.js');
const dishesInScheduleItem = require('./dishes-in-schedule-item/dishes-in-schedule-item.service.js');
const additionalProductsForItem = require('./additional-products-for-item/additional-products-for-item.service.js');
const itemStatus = require('./item-status/item-status.service.js');
const customerDeliveryAddresses = require('./customer-delivery-addresses/customer-delivery-addresses.service.js');
const products = require('./products/products.service.js');
const dishPhotos = require('./dish-photos/dish-photos.service.js');
const restaurantPhotos = require('./restaurant-photos/restaurant-photos.service.js');
const dishProducts = require('./dish-products/dish-products.service.js');
const productCategories = require('./product-categories/product-categories.service.js');
const orders = require('./orders/orders.service.js');
const orderStatus = require('./order-status/order-status.service.js');
const paymentTypes = require('./payment-types/payment-types.service.js');
const prefCustPaymentTypes = require('./pref-cust-payment-types/pref-cust-payment-types.service.js');
const orderDishes = require('./order-dishes/order-dishes.service.js');
const additionalProductsForOrder = require('./additional-products-for-order/additional-products-for-order.service.js');
const promotions = require('./promotions/promotions.service.js');
const dishesInPromotion = require('./dishes-in-promotion/dishes-in-promotion.service.js');
const foodDelivery = require('./food-delivery/food-delivery.service.js');
const tables = require('./tables/tables.service.js');
const reservations = require('./reservations/reservations.service.js');
const tablesInReservation = require('./tables-in-reservation/tables-in-reservation.service.js');
const tablesInOrder = require('./tables-in-order/tables-in-order.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function(app) {
  app.configure(restaurantdb);
  app.configure(restaurants);
  app.configure(restschedule);
  app.configure(customers);
  app.configure(customService);
  app.configure(addresses);
  app.configure(cities);
  app.configure(countries);
  app.configure(menu);
  app.configure(menuCategories);
  app.configure(restaurantDishes);
  app.configure(restDishSizes);
  app.configure(dishSizes);
  app.configure(dishesInMenu);
  app.configure(scheduleItems);
  app.configure(dishesInScheduleItem);
  app.configure(additionalProductsForItem);
  app.configure(itemStatus);
  app.configure(customerDeliveryAddresses);
  app.configure(products);
  app.configure(dishPhotos);
  app.configure(restaurantPhotos);
  app.configure(dishProducts);
  app.configure(productCategories);
  app.configure(orders);
  app.configure(orderStatus);
  app.configure(paymentTypes);
  app.configure(prefCustPaymentTypes);
  app.configure(orderDishes);
  app.configure(additionalProductsForOrder);
  app.configure(promotions);
  app.configure(dishesInPromotion);
  app.configure(foodDelivery);
  app.configure(tables);
  app.configure(reservations);
  app.configure(tablesInReservation);
  app.configure(tablesInOrder);
};
